### ISSUE TITLE
how to get bert_base uncased model (model.bin file)

### ISSUE THREAD

**Issue by PJRahul** [kamalkraj/BERT-SQuAD#4]
The model for this application generated using BERT-Large uncase. this application takes time to run in our laptops and local desktops. could u please provide a smaller version of model also could you please let us know how to train our own model to run this application.

**Comment by kamalkraj** [comment]
The pre-trained model is from https://github.com/huggingface/transformers.
They have documentation on training a QA model using different configurations, with reduced size and all.

**Comment by PJRahul** [comment]
thanks
