### ISSUE TITLE
pytorch_transformers import error

### ISSUE THREAD

**Issue by ghost** [kamalkraj/BERT-SQuAD#6]
Hello,

I've run into a strange issue. I first tested the code and it worked without any problems. However, suddenly after changing absolutely nothing, I'm getting the error:

ModuleNotFoundError: No module named 'pytorch_transformers'

I've definitely installed all of the requirements and I have no idea what is happening. Any advice?

**Comment by 21jun** [comment]
I had same problem.
You can use 'transformers' instead of 'pytorch_transformers'

change your code where import "pytorch_transformers" to "import transformers"

it's because huggingface/pytorch_transformers repository recently(?) change name to transformers

type "pip freeze" to check it out.

**Comment by ghost** [comment]
Thank you!
